### ISSUE TITLE
게시글 제목에 말머리 이모티콘이 있을 시 가리는 기능 추가 관련

### ISSUE THREAD

**Issue by pepsiricano** [incheon-kim/dogdrip_plusplus#6]
오랜만입니다.

요즘 바빠서 신경을 못쓰고 있었는데, 좀 정리가 되서 다시 신경을 써보려고 합니다ㅋㅋ

게시글 제목에 말머리 이모티콘이 있을 시 가리는 기능을 추가해보려고 하는데 어떻게 생각들 하시나요?

**Comment by incheon-kim** [comment]
저도 나쁘지 않은 기능 같다고 생각해요. 추가로 약후 가리는 기능도 좋을 것 같네요

**Comment by pepsiricano** [comment]
@incheon-kim 넵 그럼 +약후 가리는 기능까지 해서 작업 진행 해보겠습니다.

**Comment by incheon-kim** [comment]
기여 감사합니다. 수일 내로 크롬 웹스토어에도 반영 될 예정입니다.
다만 Class로 변경한 부분은 static method로 바꾸는게 맞을 것같아 해당 사항 수정하려고 합니다 :)

**Comment by incheon-kim** [comment]
0.0.4 크롬웹스토어에 게시되었습니다 :)
