### ISSUE TITLE
차단기능관련 버그발생.

### ISSUE THREAD

**Issue by emperor416** [incheon-kim/dogdrip_plusplus#9]
사용 환경 : 네이버웨일

1.  차단할 유저가 늘어서 차단하려고 클릭했더니. 아이디 클릭시 차단이 제한이 걸린것처럼 차단 메뉴가 뜨지 않음. 
2. 차단한 목록 내보내기후에 다시 불러오기 해도 마찬가지.
3. 앱업데이트문제인가 싶어서 확장프로그램을 재설치 몇번 시도 했으나 동일증상.
4. 혹시나 json파일이 문제인가 싶어서 초기화후 불러오기 를 안하고 임의의 유저를 차단 시도하니 차단기능 정상적으로 작동.
5. 다시 차단 목록(새로운 차단 목록) 내보내기후 불러오기 하니 1과 같은 오류 발생. 심지어 차단기능이 정상적으로 작동되지않음.
6. 브라우저 껐다가 키면 정상작동.

**Comment by incheon-kim** [comment]
혹시 얼마나 많이 차단 했는지
혹시 차단 메뉴가 뜨지 않았을때 F12(개발자 도구)의 콘솔(Console)에 무엇이 뜨는지 여쭤볼 수 있을까요?

**Comment by emperor416** [comment]
음 지금 확인하려고 보니까 갑자기 개드립서버점검중이라네요. 이따가 한번 해볼게요.

**Comment by emperor416** [comment]
![image](https://user-images.githubusercontent.com/24860460/158567212-c968c14f-2bba-446d-8de0-589fa683c2a2.png)

![image](https://user-images.githubusercontent.com/24860460/158567270-648be3c5-46f7-408c-a6bf-55750b490030.png)

**Comment by emperor416** [comment]
위에가 초기화 했을때 클릭하면 나오는 예시고, 밑에가 차단이 뜨지 않을때 예시입니다.

**Comment by incheon-kim** [comment]
@emperor416 해당 문제 1.1.0 에서 해결되었습니다. 크롬 웹스토어/파이어폭스 애드온 두 곳 모두 검토 대기중입니다 :)
